### ISSUE TITLE
Programs loaded with libnsocker-preload.so does not listen on local ports.

### ISSUE THREAD

**Issue by alpominth** [rkapl/nsocker#2]
Easy to reproduce:

```
$ LD_PRELOAD=/dev/shm/nsocker/build/libnsocker-preload.so NSOCKER_SERVER=/dev/shm/sock socks -l -p1080
240608033803.324 1080 00000 - 0.0.0.0:1080 0.0.0.0:0 0 0 0 Accepting connections [1577934/1757294784]
```

```
$ netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
```

@rkapl 
Could you fix this behavior?

**Comment by rkapl** [comment]
Hello, I do not know what is thet `socks` program, so I chcked with netcat like this: 
```LD_PRELOAD=libnsocker-preload.so NSOCKER_SERVER=./sock nc -l 1234```

I got:
```
[roman@rntb installed]$ netstat -nlp | grep 1234
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:1234            0.0.0.0:*               LISTEN      233541/nc
```
Could you point me to what is the `socks` program, or what is it trying to do? Or try running it with strace.

**Comment by alpominth** [comment]
Sorry for the misleading post.

I started nsocker daemon in the host network:

sudo -u user nsocker -f /tmp/blah

And:

`unshare -n sudo -u user mate-terminal`

A terminal shell was unshared from the host network, I had to bring loopback up inside the netns with `ip link set lo up`

In the unshared terminal I run `nc`

LD_PRELOAD="./nsocker/build/libnsocker-preload.so" NSOCKER_SERVER=/tmp/blah nc -l 1234

When I try to check the listening point inside the netns of unshared terminal I get:

```
$ netstat -nlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     67102    195716/dbus-daemon   /tmp/dbus-kmlvuCL5uM
```

But I realized that nc listens in the host network:

```
$ netstat -nlp | grep 1234
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:1234            0.0.0.0:*               LISTEN      196936/nc  
```

Resuming: What I was trying to achieve is to run a program in a isolated netns and use the host network while keeping the program listening in the isolated netns.

>Could you point me to what is the socks program, or what is it trying to do? Or try running it with strace.

`socks`  is a app that is shipped with [3proxy](https://github.com/3proxy/3proxy), I tested with some other LD_PRELOAD tricks and work fine, it wouldn't be different with nsocker lib.

**Comment by alpominth** [comment]
I got the point of nsocker: Use the network of a netns without root.

I was confused because I thought nsocker were doing almost the same of xsocket: https://github.com/koro666/xsocket

It is: start nsocker-daemon in a netns, trick the program with nsocker-library and make it run in that netns.

Thanks.

**Comment by rkapl** [comment]
Oh, I am starting to understand. If I understand correctly you want the proxy to listen in host namespaces, while still creating outgoing connections in guest namespace.

Yes, nsocker-preload will create both sockets in the host namespace in your case. You would need nsocker-aware application to create only some sockets in the remote namspace. I currently do not have plans to do something like xsocket does, where it works only for certain ports.

Btw, have you considered using veth pairs to connect the two namespaces? I think it would work for your use case and allow the socks proxy to be accessible from the host namespace.

**Comment by alpominth** [comment]
>Oh, I am starting to understand. If I understand correctly you want the proxy to listen in host namespaces, while still creating outgoing connections in guest namespace.

Yes, that is it.

>Btw, have you considered using veth pairs to connect the two namespaces? I think it would work for your use case and allow the socks proxy to be accessible from the host namespace.

What I'm trying to do is to make a TPROXY server listen in the guest netns and send its outgoing connection to the host netns (netns of pid #1, `nsenter -t 1 n`). I can make the opposite with xsocket, TPROXY server starts in the host netns and listen its ports in the guest netns, but for TPROXY server working with UDP, the address of subnet inside the netns should be routable to the host for work with UDP, making a veth pair connecting the inner subnet of the guest netns to the host one could introduce a security issue.

Indeed, I'm using veth pairs right now, I start a (3proxy) socks server listening in the veth and the TPROXY server listening in the guest netns connecting to the nexthop (host side veth). I was trying to find a way to get rid of them because it could remove one layer of overhead (the socks server).

Thanks.
